version: '3.7'
networks:
  elka:
services:
  elasticsearch:
    image: elasticsearch:8.3.1
    container_name: elasticsearch
    environment:
      - opendistro_security.disabled=true
      - cluster.name=mycluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - "d:/www/docker/elk/data:/usr/share/elasticsearch/data"
    ports:
      - 9200:9200
    #  - 9600:9600 # required for Performance Analyzer
    networks:
      - elka

  kibana:
    image: kibana:8.3.1

    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elka